chore: add submodule with relative URL to .gitmodules
python-poetry/test-fixture-vcs-repository pull request #4
Opened 2022-09-21 14:08 UTC by evanrittenhouse

2022-09-24 19:24 UTC, evanrittenhouse commented
CC @neersighted. I think this is what we're looking for, have never really worked with submodules. From what I understand of the integration tests, I won't be able to move forward until this is merged.

2022-09-25 00:23 UTC, neersighted commented
This is incorrect -- let me try and fix it up for you.

2022-09-25 00:24 UTC, neersighted requested changes

2022-09-25 00:24 UTC, neersighted commented on .gitmodules
> +	url = ./submodules/relative-url-submodule.git
```suggestion
[submodule "submodules/relative-url-submodule"]
	path = submodules/relative-url-submodule
	url = ../test-fixture-vcs-repository.git
```

2022-09-25 00:24 UTC, neersighted commented on .gitmodules
> +	url = ./submodules/relative-url-submodule.git
You'll need to make sure that the submodule ref is pinned to the branch I created for you as well.

2022-09-25 03:36 UTC, evanrittenhouse commented
@neersighted appreciate the feedback. Updates made.

2022-10-01 15:10 UTC, evanrittenhouse commented
@neersighted just bumping this

2022-10-01 15:36 UTC, closed without merging